name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        #- name: macOS
        #  os: macos-latest

        #- name: iOS
        #  os: macos-latest
        #  target: iOS

        #- name: Android32
        #  os: ubuntu-latest
        #  target: Android32

        #- name: Android64
        #  os: ubuntu-latest
        #  target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Scoop # installing scoop because i dont trust winget
        uses: MinoruSekine/setup-scoop@v3
        with:
          buckets: extras

      - name: Setup Geode and sccache
        run: |
          scoop install sccache
          scoop bucket add extras
          scoop install geode-sdk-cli
          geode profile add --name helloWorld C:/ # dont need a profile but it refuses to run without one
          echo y | geode sdk install
          echo "GEODE_SDK=C:\Users\runneradmin\Documents\Geode" >> $env:GITHUB_ENV

      - name: Install Geode Binaries
        run: geode sdk install-binaries

      - name: Compile
        run: |
          $clangPath = (Get-Command clang++).Source
          $clangCPath = (Get-Command clang).Source
          cmake -B build -G "Ninja" `
            -DCMAKE_C_COMPILER="$clangCPath" `
            -DCMAKE_CXX_COMPILER="$clangPath" `
            -DCMAKE_C_COMPILER_LAUNCHER=sccache `
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache `
            -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build --config RelWithDebInfo

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          if-no-files-found: error
          name: Build
          path:  ${{ github.workspace }}\.output\**\*